import Head from 'next/head'
import { Flex, Center, SimpleGrid, Box } from '@chakra-ui/react'
import Header from '@/components/Header/Header'
import { useAccount } from 'wagmi'
import AddJob from '@/components/AddJob/AddJob'
import MyJob from '@/components/MyJob/MyJob'
import YourJob from '@/components/YourJob/YourJob'
import Link from 'next/link'

export default function Home() {
  const { address, isConnected } = useAccount()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {isConnected ? (
        <>
          <AddJob />
          <SimpleGrid columns={2} spacing={10}>
            <MyJob />
            <YourJob />
          </SimpleGrid>
        </>
      ) : (
        <Center bg='tomato' h='100px' color='white'>
          Veuillez vous connecter
        </Center>
      )}
    </>
  )
}
